import api from '../api/client';
const unwrap = (promise) => promise.then((r) => r.data.data);
export const authApi = { login: (body) => unwrap(api.post('/auth/login', body)), register: (body) => unwrap(api.post('/auth/register', body)), me: () => unwrap(api.get('/auth/me')) };
export const vehicleApi = {
  brands: () => unwrap(api.get('/brands')), models: (id) => unwrap(api.get(id ? `/models/brand/${id}` : '/models')), variants: (id) => unwrap(api.get(id ? `/variants/model/${id}` : '/variants')),
  createBrand: (b) => unwrap(api.post('/brands', b)), updateBrand: (id,b) => unwrap(api.put(`/brands/${id}`,b)), deleteBrand: (id) => unwrap(api.delete(`/brands/${id}`)),
  createModel: (b) => unwrap(api.post('/models', b)), updateModel: (id,b) => unwrap(api.put(`/models/${id}`,b)), deleteModel: (id) => unwrap(api.delete(`/models/${id}`)),
  createVariant: (b) => unwrap(api.post('/variants', b)), updateVariant: (id,b) => unwrap(api.put(`/variants/${id}`,b)), deleteVariant: (id) => unwrap(api.delete(`/variants/${id}`)),
  saved: () => unwrap(api.get('/my-cars')), addSaved: (b) => unwrap(api.post('/my-cars',b)), updateSaved: (id,b) => unwrap(api.put(`/my-cars/${id}`,b)), deleteSaved: (id) => unwrap(api.delete(`/my-cars/${id}`)) };
export const catalogApi = { list: (params) => unwrap(api.get('/catalog',{params})), one: (id) => unwrap(api.get(`/catalog/${id}`)) };
export const productApi = { list: (params) => api.get('/products',{params}).then(r=>r.data), one:(id)=>unwrap(api.get(`/products/${id}`)), create:(b)=>unwrap(api.post('/products',b)), update:(id,b)=>unwrap(api.put(`/products/${id}`,b)), delete:(id)=>unwrap(api.delete(`/products/${id}`)), images:(id,files)=>{const f=new FormData();Array.from(files).forEach(x=>f.append('images',x));return unwrap(api.post(`/products/${id}/images`,f))}, compatibility:(id)=>unwrap(api.get(`/products/${id}/compatibility`)), addCompatibility:(id,variantIds)=>unwrap(api.post(`/products/${id}/compatibility`,{variantIds})), removeCompatibility:(id,v)=>unwrap(api.delete(`/products/${id}/compatibility/${v}`)) };
export const campaignApi = { list:()=>unwrap(api.get('/campaigns')), one:(id)=>unwrap(api.get(`/campaigns/${id}`)), create:(b)=>unwrap(api.post('/campaigns',b)), delete:(id)=>unwrap(api.delete(`/campaigns/${id}`)), users:(id)=>unwrap(api.get(`/campaigns/${id}/users`)), send:(id)=>api.post(`/campaigns/${id}/send`).then(r=>r.data) };
