import { useState } from 'react';
import { Link, Navigate, Route, Routes, useNavigate, useParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CarFront, LogOut, Plus } from 'lucide-react';
import { toast } from 'sonner';
import { useAuth } from './context/AuthContext';
import { authApi, carsApi, catalogApi, productApi } from './services/api';

const errorMessage = (e) => e.response?.data?.message || e.message || 'Something went wrong';
const money = (value) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(value || 0);

function Shell({ children, admin = false }) { const { user, isAdmin, logout } = useAuth(); const nav = useNavigate(); return <><header className={admin ? 'border-b bg-slate-950 text-white' : 'sticky top-0 z-10 border-b bg-white/95 backdrop-blur'}><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4"><Link to={admin ? '/admin' : '/'} className="flex items-center gap-2 text-xl font-black"><CarFront className="text-orange-500" />CarShop{admin && ' Admin'}</Link><nav className="hidden gap-5 sm:flex">{(admin ? [['/admin', 'Dashboard'], ['/admin/products', 'Products'], ['/admin/vehicles', 'Vehicles'], ['/admin/campaigns', 'Campaigns']] : [['/catalog', 'Shop'], ['/saved-cars', 'My garage']]).map(([to, label]) => <Link key={to} to={to} className="text-sm font-medium hover:text-orange-500">{label}</Link>)}</nav><div className="flex gap-2">{user ? <><span className="hidden self-center text-sm sm:block">{user.name}</span>{!admin && isAdmin && <Link className="btn-secondary" to="/admin">Admin</Link>}<button className="btn-secondary" onClick={() => { logout(); nav('/'); }}><LogOut size={16} /></button></> : <><Link className="btn-secondary" to="/login">Sign in</Link><Link className="btn-primary" to="/register">Register</Link></>}</div></div></header><main className="mx-auto max-w-7xl p-4 py-8">{children}</main></>; }
function AuthPage({ register = false }) { const { setSession, user } = useAuth(); const nav = useNavigate(); const [form, setForm] = useState({ name: '', email: '', password: '' }); const mutation = useMutation({ mutationFn: () => register ? authApi.register(form) : authApi.login(form), onSuccess: (session) => { setSession(session); toast.success(register ? 'Account created' : 'Welcome back'); nav(session.user.role === 'ADMIN' ? '/admin' : '/catalog'); }, onError: (e) => toast.error(errorMessage(e)) }); if (user) return <Navigate to="/catalog" />; return <div className="mx-auto mt-12 max-w-md card p-7"><h1 className="text-2xl font-bold">{register ? 'Create your account' : 'Welcome back'}</h1><form className="mt-6 space-y-4" onSubmit={(e) => { e.preventDefault(); mutation.mutate(); }}>{register && <input className="field" placeholder="Full name" required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} />}<input className="field" type="email" placeholder="Email address" required value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /><input className="field" type="password" minLength="6" placeholder="Password" required value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /><button className="btn-primary w-full" disabled={mutation.isPending}>{register ? 'Create account' : 'Sign in'}</button></form><p className="mt-4 text-center text-sm"><Link className="text-orange-600" to={register ? '/login' : '/register'}>{register ? 'Already registered? Sign in' : 'Create an account'}</Link></p></div>; }
function Home() { return <Shell><section className="grid items-center gap-10 py-16 md:grid-cols-2"><div><p className="font-semibold text-orange-600">PERFECT FIT. EVERY TIME.</p><h1 className="mt-3 text-5xl font-black tracking-tight text-ink">Accessories that fit your car.</h1><p className="mt-5 max-w-lg text-lg text-slate-600">Save your exact vehicle, then discover compatible parts.</p><Link className="btn-primary mt-7" to="/catalog">Browse accessories</Link></div><div className="rounded-3xl bg-slate-900 p-10 text-white"><CarFront size={160} className="mx-auto text-orange-400" /><p className="text-center text-xl font-bold">Fitment-led shopping</p></div></section></Shell>; }
function Catalog() { const [savedCarId, setSavedCarId] = useState(''); const query = useQuery({ queryKey: ['catalog', savedCarId], queryFn: () => catalogApi.list(savedCarId ? { savedCarId } : undefined) }); return <Shell><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-semibold text-orange-600">FITMENT-FIRST CATALOG</p><h1 className="text-3xl font-bold">Shop accessories</h1></div><input className="field max-w-xs" placeholder="Saved car ID (optional)" value={savedCarId} onChange={(e) => setSavedCarId(e.target.value)} /></div>{query.isLoading ? <p className="mt-8">Loading products…</p> : query.isError ? <p className="mt-8 text-red-600">{errorMessage(query.error)}</p> : <div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{(query.data || []).map((p) => <Link to={`/products/${p.id}`} key={p.id} className="card p-4"><div className="flex aspect-square items-center justify-center rounded-lg bg-slate-100"><CarFront className="text-slate-300" size={56} /></div><p className="mt-4 text-sm text-orange-600">Accessory</p><h2 className="mt-1 font-semibold">{p.name}</h2><p className="mt-3 font-bold">{money(p.price)}</p></Link>)}{!query.data?.length && <p className="text-slate-500">No compatible products found.</p>}</div>}</Shell>; }
function Product() { const { id } = useParams(); const query = useQuery({ queryKey: ['product', id], queryFn: () => productApi.one(id) }); if (query.isLoading) return <Shell>Loading…</Shell>; if (query.isError) return <Shell><p className="text-red-600">{errorMessage(query.error)}</p></Shell>; const p = query.data; return <Shell><Link className="text-orange-600" to="/catalog">← Back to shop</Link><div className="mt-6 grid gap-8 md:grid-cols-2"><div className="flex aspect-square items-center justify-center rounded-xl bg-slate-100"><CarFront size={100} className="text-slate-300" /></div><div><p className="text-orange-600">Car accessory</p><h1 className="mt-2 text-4xl font-bold">{p.name}</h1><p className="mt-5 text-2xl font-bold">{money(p.price)}</p><p className="mt-6 whitespace-pre-wrap text-slate-600">{p.description || 'No product description provided.'}</p><div className="mt-8 rounded-xl bg-orange-50 p-4"><h3 className="font-semibold">Compatible vehicles</h3><p className="mt-1 text-sm text-slate-600">{p.compatibleCars?.length ? p.compatibleCars.map((c) => `${c.brand} ${c.model} ${c.variant}`).join(', ') : 'No compatibility assigned.'}</p></div></div></div></Shell>; }
function Garage() { const qc = useQueryClient(); const { data: brands = [] } = useQuery({ queryKey: ['brands'], queryFn: carsApi.brands }); const [brand, setBrand] = useState(''); const [model, setModel] = useState(''); const [variant, setVariant] = useState(''); const [nickname, setNickname] = useState(''); const models = useQuery({ queryKey: ['models', brand], queryFn: () => carsApi.models(brand), enabled: !!brand }); const variants = useQuery({ queryKey: ['variants', model], queryFn: () => carsApi.variants(model), enabled: !!model }); const cars = useQuery({ queryKey: ['saved'], queryFn: carsApi.saved }); const add = useMutation({ mutationFn: () => carsApi.addSaved({ variantId: variant, nickname }), onSuccess: () => { qc.invalidateQueries({ queryKey: ['saved'] }); toast.success('Vehicle saved'); }, onError: (e) => toast.error(errorMessage(e)) }); const remove = useMutation({ mutationFn: carsApi.removeSaved, onSuccess: () => qc.invalidateQueries({ queryKey: ['saved'] }), onError: (e) => toast.error(errorMessage(e)) }); return <Shell><h1 className="text-3xl font-bold">My garage</h1><div className="card mt-6 p-5"><h2 className="font-semibold">Add a vehicle</h2><form className="mt-4 grid gap-3 md:grid-cols-4" onSubmit={(e) => { e.preventDefault(); add.mutate(); }}><select className="field" required value={brand} onChange={(e) => { setBrand(e.target.value); setModel(''); setVariant(''); }}><option value="">Brand</option>{brands.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select className="field" required disabled={!brand} value={model} onChange={(e) => { setModel(e.target.value); setVariant(''); }}><option value="">Model</option>{models.data?.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select className="field" required disabled={!model} value={variant} onChange={(e) => setVariant(e.target.value)}><option value="">Variant</option>{variants.data?.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select><input className="field" placeholder="Nickname (optional)" value={nickname} onChange={(e) => setNickname(e.target.value)} /><button className="btn-primary md:col-span-4" disabled={!variant || add.isPending}>Save vehicle</button></form></div><div className="mt-6 grid gap-4 md:grid-cols-2">{cars.data?.map((c) => <div key={c.id} className="card flex items-center justify-between p-5"><div><h3 className="font-semibold">{c.nickname || `${c.brand_name} ${c.model_name}`}</h3><p className="text-sm text-slate-500">{c.brand_name} · {c.model_name} · {c.variant_name}</p></div><button className="text-sm text-red-600" onClick={() => remove.mutate(c.id)}>Remove</button></div>)}</div></Shell>; }
function Guard({ admin = false, children }) { const { user, isAdmin } = useAuth(); return !user ? <Navigate to="/login" /> : admin && !isAdmin ? <Navigate to="/" /> : children; }
function AdminProducts() { const qc = useQueryClient(); const products = useQuery({ queryKey: ['admin-products'], queryFn: () => productApi.list({ limit: 50 }) }); const remove = useMutation({ mutationFn: productApi.remove, onSuccess: () => { qc.invalidateQueries({ queryKey: ['admin-products'] }); toast.success('Product deleted'); } }); return <Shell admin><div className="flex items-center justify-between"><h1 className="text-3xl font-bold">Products</h1><Link to="/admin/products/new" className="btn-primary"><Plus size={16} />New product</Link></div><div className="card mt-6 overflow-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-4">Product</th><th>Price</th><th>Actions</th></tr></thead><tbody>{products.data?.data?.map((p) => <tr className="border-t" key={p.id}><td className="p-4 font-medium">{p.name}</td><td>{money(p.price)}</td><td><Link className="mr-3 text-orange-600" to={`/admin/products/${p.id}`}>Edit</Link><button className="text-red-600" onClick={() => remove.mutate(p.id)}>Delete</button></td></tr>)}</tbody></table></div></Shell>; }
function Dashboard() { return <Shell admin><h1 className="text-3xl font-bold">Dashboard</h1><p className="mt-2 text-slate-600">Manage your catalog, vehicle fitment and campaigns.</p></Shell>; }
function App() { return <Routes><Route path="/" element={<Home />} /><Route path="/catalog" element={<Catalog />} /><Route path="/products/:id" element={<Product />} /><Route path="/login" element={<AuthPage />} /><Route path="/register" element={<AuthPage register />} /><Route path="/saved-cars" element={<Guard><Garage /></Guard>} /><Route path="/admin" element={<Guard admin><Dashboard /></Guard>} /><Route path="/admin/products" element={<Guard admin><AdminProducts /></Guard>} /><Route path="*" element={<Navigate to="/" />} /></Routes>; }
export default App;
